dashboard/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from stock import views as stock
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock.urls' , namespace='stock')),
    path('categories/', stock.manage_categories, name='manage_categories'),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/urls.py
from django.urls import path, re_path
from . import views
from stock.views import DetailViewss, ProductCreate, ProductDelete, ProductUpdate,CategoryCreate, CategoryUpdate,CategoryDelete, ListTransaksi, TransaksiDelete, RecentTransaksiDelete
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.browse, name='dashboard'),

    # path('<x:pk>/delete/', views.delete_transaksi, name='transaksi-delete'),
    # path('delete/<int:id>/', views.delete_transaksi, name='transaksi-delete'),

    path('<int:pk>-<slug:slug>/', DetailViewss.as_view(), name='detail_product'),
    
    path('transaksi/', ListTransaksi.as_view(), name='transaction_list'),
    path('earnings/', views.ListEarning, name='earnings'),
    path('earnings/year/', views.ListEarning_Year, name='earnings_year'),
    path('chart/', views.chart, name='chart'),
    path('year_chart/', views.year_chart, name='year_chart'),

    path('submit/', ProductCreate.as_view(), name='author-add'),
    path('submitkategori/', CategoryCreate.as_view(), name='category-add'),

    path('<int:pk>-<slug:slug>/update/', ProductUpdate.as_view(), name='author-update'),
    path('<int:pk>-<slug:slug>/delete/', ProductDelete.as_view(), name='author-delete'),
    
    path('<slug:slug>/update/', CategoryUpdate.as_view(), name='category-update'),
    path('<slug:slug>/delete/', CategoryDelete.as_view(), name='category-delete'),

    path('transaksi/<int:pk>/delete/', TransaksiDelete.as_view(), name='transaksi-delete'),
    path('recent/<int:pk>/delete/', RecentTransaksiDelete.as_view(), name='recent-transaksi-delete'),
]

app_name='stock'

stock/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
from django.db.models import F, Sum
from django.db.models.signals import pre_delete
from django.dispatch import receiver
# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    harga_jual = models.DecimalField(max_digits=14 , decimal_places=2)
    harga_modal = models.DecimalField(max_digits=14, decimal_places=2)
    quantity = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey('Kategori', on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='poster/' , blank=True , null=True)
    slug = models.SlugField(blank=True , null=True)
    supplier = models.CharField(max_length=100,null=True,blank=True)

    def save(self, *args , **kwargs):
        if not self.slug and self.name :
            self.slug = slugify(self.name)
        super(Product , self).save(*args , **kwargs)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('stock:detail_product', kwargs={'pk': self.pk , 'slug': self.slug})

    @property
    def get_photo_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return "/static/images/user.jpg"

class Kategori(models.Model):
    category_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='kategori/' , blank=True , null=True)
    slug = models.SlugField(blank=True , null=True)
    def save(self, *args , **kwargs):
        if not self.slug and self.category_name :
            self.slug = slugify(self.category_name)
        super(Kategori , self).save(*args , **kwargs)

    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return reverse('stock:dashboard')

class Transaksi(models.Model):
    items = models.ForeignKey(Product,on_delete=models.PROTECT, null=True)
    purchase_date = models.DateTimeField(default=timezone.now)
    sold_quantity = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    harga_terjual = models.DecimalField(max_digits=14, decimal_places=2, default=0)


    def save(self, *args, **kwargs):
        super(Transaksi, self).save(*args, **kwargs)
        self.items.quantity -= self.sold_quantity
        self.items.save()
    
    def delete(self, *args, **kwargs):
        self.items.quantity += self.sold_quantity
        self.items.save()
        super(Transaksi, self).delete(*args, **kwargs)

    def __str__(self):
        return str(self.id)
    
    @property
    def total(self):
        return int(self.sold_quantity * self.harga_terjual)

stock/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product , Kategori, Transaksi
from django.db.models import Count, Q, Sum, F, Value
from .forms_submit import IssueForm
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormMixin
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.db.models.functions import TruncDate, TruncMonth, TruncYear
from datetime import datetime
import calendar
from .filters import Filter, Filter2
from django.template.loader import render_to_string
from django.http import JsonResponse
# Create your views here.


def browse (request):
    category = None
    listproduct = Product.objects.all()
    listkategori = Kategori.objects.annotate(totalkategori = Count('product'))
    harga = request.GET.get('harga', None)
    nama = request.GET.get('nama', None)

    search_query= request.GET.get('q')
    if search_query :
        listproduct = listproduct.filter(
            Q(name__icontains = search_query)|
            Q(description__icontains = search_query)
        )
	

    if harga == "hargaplus":
        listproduct = listproduct.order_by('harga_jual')
    elif harga == "hargamin":
        listproduct = listproduct.order_by('-harga_jual')
    
    if nama == "namaplus":
        listproduct = listproduct.order_by('name')
    elif nama == "namamin":
        listproduct = listproduct.order_by('-name')


    if request.is_ajax():
        html = render_to_string(
            template_name="stock/results-partial.html", 
            context={"list_product": listproduct}
        )
        data_dict = {"html_from_view": html}
        return JsonResponse(data=data_dict, safe=False)

    # paginator = Paginator(listproduct, 40)
    # page_number = request.GET.get('page')
    # listproduct = paginator.get_page(page_number)
    template = 'stock/dashboard.html'
    
    context = {'list_product' : listproduct , 'list_kategori' : listkategori}
    return render(request, template , context)

def ListEarning (request):
    data = request.GET.copy()

    if 'purchase_month' not in data:
        data['purchase_month'] = datetime.now().month

    if 'purchase_year' not in data: 
        data['purchase_year'] = datetime.now().year
    
    data_hari = Transaksi.objects.all().annotate(date=TruncDate('purchase_date')).values('date').annotate(total_sales=Sum(F('harga_terjual')*F('sold_quantity')))
    data_filter = Filter(data, queryset=data_hari)
    month = calendar.month_name[int(data_filter.data['purchase_month'])]
    month_earning = Transaksi.objects.filter(purchase_date__month=data['purchase_month']).annotate(date=TruncMonth('purchase_date')).values('date').annotate(total_sales=Sum(F('harga_terjual')*F('sold_quantity')), total_margin=Sum( ( F('harga_terjual')-F('items__harga_modal') )*F('sold_quantity') ))

    template = 'stock/profit.html'
    
    context = {'filter': data_filter, 'month': month, 'month_earning' : month_earning }
    return render(request, template , context)

def ListEarning_Year (request):
    data = request.GET.copy()

    if 'purchase_year' not in data: 
        data['purchase_year'] = datetime.now().year
    
    data_bulan = Transaksi.objects.filter(purchase_date__year=data['purchase_year']).annotate(date=TruncMonth('purchase_date')).values('date').annotate(total_sales=Sum(F('harga_terjual')*F('sold_quantity')),  total_margin=Sum( ( F('harga_terjual')-F('items__harga_modal') )*F('sold_quantity') ))

    data_filter = Filter2(data, queryset=data_bulan)

    year_earning = Transaksi.objects.filter(purchase_date__year=data['purchase_year']).annotate(date=TruncYear('purchase_date')).values('date').annotate(total_sales=Sum(F('harga_terjual')*F('sold_quantity')),  total_margin=Sum( ( F('harga_terjual')-F('items__harga_modal') )*F('sold_quantity') ))
    
    template = 'stock/profit_year.html'
    
    context = {'filter': data_filter, 'year_earning' : year_earning}
    return render(request, template , context)
    
def chart(request):
    data = request.GET.copy()

    if 'purchase_month' not in data:
        data['purchase_month'] = datetime.now().month

    if 'purchase_year' not in data: 
        data['purchase_year'] = datetime.now().year
    
    data_hari = Transaksi.objects.filter(purchase_date__month=data['purchase_month']).annotate(date=TruncDate('purchase_date')).values('date').annotate( total_sales=Sum( F('harga_terjual')*F('sold_quantity')), total_margin=Sum( ( F('harga_terjual')-F('items__harga_modal') )*F('sold_quantity') )).values('date','total_sales','total_margin')

    data_filter = Filter(data, queryset=data_hari)
    month = calendar.month_name[int(data_filter.data['purchase_month'])]
    
    data_product = Transaksi.objects.filter(purchase_date__month=data['purchase_month']).values('items__category__category_name').annotate(total_quantity=Sum('sold_quantity'))
    
    template = 'stock/chart.html'  
    context = { 'filter' : data_filter, 'month': month, 'data_product' : data_product }
    return render(request, template , context)
  
def year_chart(request):
    data = request.GET.copy()

    if 'purchase_year' not in data: 
        data['purchase_year'] = datetime.now().year
    
    data_bulan = Transaksi.objects.filter(purchase_date__year=data['purchase_year']).annotate(date=TruncMonth('purchase_date')).values('date').annotate( total_sales=Sum( F('harga_terjual')*F('sold_quantity')), total_margin=Sum( ( F('harga_terjual')-F('items__harga_modal') )*F('sold_quantity') )).values('date','total_sales','total_margin')

    data_filter = Filter2(data, queryset=data_bulan)
    year = data_filter.data['purchase_year']
    
    data_product = Transaksi.objects.filter(purchase_date__year=data['purchase_year']).values('items__category__category_name').annotate(total_quantity=Sum('sold_quantity'))
    
    template = 'stock/year_chart.html'  
    context = { 'filter' : data_filter, 'year': year, 'data_product' : data_product }
    return render(request, template , context)
  
def manage_categories(request, slug=None):
    listkategori = Kategori.objects.annotate(totalkategori = Count('product'))
    template = 'stock/categories.html'  
    context = { 'list_kategori' : listkategori}
    return render(request, template , context)

class ListTransaksi(ListView):
    model = Transaksi
    paginate_by = 100
    template_name = 'stock/transaksi.html'
    context_object_name = "data_transaksi"
    ordering = ['-purchase_date']

class DetailViewss(FormMixin, DetailView):
    model = Product
    template_name = 'stock/detail.html'  
    form_class = IssueForm
    
    def get_success_url(self):
        return reverse('stock:detail_product', kwargs={'slug': self.object.slug , 'pk':self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(DetailViewss, self).get_context_data(**kwargs)
        data_transaksi = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        daftar_transaksi = data_transaksi.transaksi_set.all()
        daftar_transaksi = daftar_transaksi.order_by('-purchase_date')
        paginator = Paginator(daftar_transaksi,15)
        page = self.request.GET.get('page')
        daftar_transaksi = paginator.get_page(page)
        context['form'] = IssueForm(initial={
            'items': data_transaksi,
            'sold_quantity' : 1,
            'harga_terjual' : data_transaksi.harga_jual
        })
        context["detail_product"] = self.object
        context['data_transaksi'] = daftar_transaksi
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(DetailViewss, self).form_valid(form)

def delete_transaksi(request, id):
    query = get_object_or_404(Transaksi, id=id)
    query.delete()
    return HttpResponseRedirect(reverse('stock:dashboard'))

class ProductCreate(CreateView):
    model = Product
    fields = ['name','description','harga_modal','supplier','harga_jual','quantity','category','image']
    success_url = '/'
    template_name = 'stock/submit.html'
    def form_valid(self, form):
        aa = form.save(commit=False)
        aa.save()
        return super().form_valid(form)

class ProductUpdate(UpdateView):
    model = Product
    fields = ['name','description','harga_modal','harga_jual','quantity','category','image']
    template_name = 'stock/post_update.html'
    def test_func(self):
        return True

class ProductDelete(DeleteView):
    model = Product
    success_url = '/'

    def test_func(self):
        return True

class CategoryCreate( CreateView):
    model = Kategori
    fields = ['category_name']
    
    template_name = 'stock/submit.html'
    def form_valid(self, form):
        return super().form_valid(form)

class CategoryUpdate(UpdateView):
    model = Kategori
    fields = ['category_name']
    template_name = 'stock/post_update.html'
    def test_func(self):
        return True

class CategoryDelete(DeleteView):
    model = Kategori
    success_url = '/'

    def test_func(self):
        return True

class TransaksiDelete(DeleteView):
    model = Transaksi
    success_url = '/'

    def test_func(self):
        return True
    
    def get_success_url(self):
        # Assuming there is a ForeignKey from Comment to Post in your model
        items = self.object.items
        return reverse_lazy( 'stock:detail_product', kwargs={'pk': items.pk , 'slug':items.slug})

stock/templates/stock/categories.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- KANAN -->
<div class="main-panel">
  <div class="content-wrapper">

    <div class="row">
      <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between flex-wrap">
          <div class="d-flex align-items-end flex-wrap">
            <div class="mr-md-3 mr-xl-5">
              <h2>Manage Categories</h2>
            </div>
          </div>
          <div class="d-flex justify-content-between align-items-end flex-wrap">
            <div class="nav-item">
              <a class="btn btn-primary mt-2 mt-xl-0" href="{% url 'stock:author-add'%}">Add Product</a>
              <a class="btn btn-primary mt-2 mt-xl-0 btn-hijau btn-nico" href="{% url 'stock:category-add'%}">Add Category</a>
            </div>
          </div>
        </div>
      </div>
    </div>

     <div class="row">
      <div class="col-md-12 grid-margin">
        {% for Kategori in list_kategori %}
            <div class="luar d-flex justify-content-between flex-wrap baris">
            
                <div class="d-flex align-items-end flex-wrap">
                    <div class="mr-md-3 mr-xl-5">
                        <h4 class="title">{{Kategori.category_name}}</h4>
                        <p class="mb-md-0">Jumlah : {{Kategori.totalkategori}}</p>
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-end flex-wrap">
                    <div class="nav-item">
                        <a class="btn btn-primary mt-2 mt-xl-0" href="{% url 'stock:category-update' Kategori.slug %}">Edit</a>
                        <a class="btn btn-primary mt-2 mt-xl-0 btn-merah btn-nico" href="{% url 'stock:category-delete' Kategori.slug %}">Delete</a>
                    </div>
                </div>
          
            </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock content %}

stock/templates/stock/chart.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

<!-- KANAN -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<div class="main-panel">
    <div class="content-wrapper">   
        <div class="tab detail-page">
            <button class="tablinks" onclick="openChart(event, 'Earnings')" id="defaultOpen">Earnings</button>
            <button class="tablinks" onclick="openChart(event, 'Margins')">Margins</button>
            <button class="tablinks" onclick="openChart(event, 'Items')">Items</button>
            <script>document.getElementById("defaultOpen").click();</script>
        </div>

          <!-- Tab content -->
        <div id="Earnings" class="chart-page detail-page tabcontent">
            <div class='chart-box '>
                <h2 class='chart-title'>Total Pembelian Bulan {{month}}</h2>
                <canvas id="chart_earnings" width="300" height="150"></canvas>
            </div>
            <script>
                function getColors(){
                    let pallet = ['rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'];
                    let colors = [];
                    for(let i = 0; i < 30; i++) {
                        colors.push(pallet[i % pallet.length]);
                    }
                    return colors;
                }
                var ctx = document.getElementById('chart_earnings').getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: [ {% for transaksi in filter.qs %} '{{ transaksi.date }}', {% endfor %} ],
                        datasets: [{
                            label: 'Sold Quantity',
                            data: [{% for transaksi in filter.qs %} {{ transaksi.total_sales|safe }}, {% endfor %}],
                            backgroundColor: getColors(),
                            borderColor: getColors(),
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                });
            </script>
        </div>
          
        <div id="Margins" class="detail-page tabcontent">
            <div class='chart-box '>
                <h2 class='chart-title'>Total Pendapatan Bersih Bulan {{month}}</h2>
                <canvas id="chart_margins" width="300" height="150"></canvas>
            </div>
            <script>
                var ctx = document.getElementById('chart_margins').getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: [ {% for transaksi in filter.qs %} '{{ transaksi.date }}', {% endfor %} ],
                        datasets: [{
                            label: 'Sold Quantity',
                            data: [{% for transaksi in filter.qs %} {{ transaksi.total_margin|safe }}, {% endfor %}],
                            backgroundColor: getColors(),
                            borderColor: getColors(),
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                });
            </script>
        </div>
        <div id="Items" class="detail-page tabcontent">
            <div class='chart-box '>
                <h2 class='chart-title'>Jumlah Item Keluar Bulan {{month}}</h2>
                <canvas id="chart_items" width="300" height="150"></canvas>
            </div>
            <script>
                var ctx = document.getElementById('chart_items').getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'pie',
                    data: {
                        labels: [ {% for Transaksi in data_product %} '{{ Transaksi.items__category__category_name  }}', {% endfor %} ],
                        datasets: [{
                            label: 'Sold Quantity',
                            data: [{% for Transaksi in data_product %} {{ Transaksi.total_quantity|safe }}, {% endfor %}],
                            backgroundColor: getColors(),
                            borderColor: getColors(),
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                });
            </script>
        </div>  

        <div class="detail-page luar">
            <form method="GET" class="filter-bar">
                <div class="filtering">
                    <div>
                        {{ filter.form.non_field_errors }}
                        <div class="fieldWrapper">
                            {{ filter.form.purchase_month.errors }}
                            <label style='margin-left:20px; color:rgb(51, 51, 51);' for="{{ filter.form.purchase_month.id_for_label }}">Penghasilan Bulan : </label>
                            {{ filter.form.purchase_month|add_class:'filter-field btn'}}
                        </div>
                    </div>
                    <div>
                        {{ filter.form.non_field_errors }}
                        <div class="fieldWrapper">
                            {{ filter.form.purchase_year.errors }}
                            <label style='margin-left:20px; color:rgb(51, 51, 51);' for="{{ filter.form.purchase_year.id_for_label }}">Tahun : </label>
                            {{ filter.form.purchase_year|add_class:'filter-field btn'}}
                        </div>
                    </div>
                    <button class="btn btn-primary mt-2 mt-xl-0 btn-nico" style='align-content: center; margin-left:10px;' type="submit">Search</button>
                    <a class="btn btn-primary mt-2 mt-xl-0 btn-nico btn-merah kanan" href="{% url 'stock:year_chart' %}">Year View</a>
                </div>
            </form>
        </div>  
    </div>

{% endblock content %}

stock/templates/stock/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- KANAN -->
<div class="main-panel">
  <div class="content-wrapper">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <div style="overflow: visible;"class="container tab detail-page">
      <button class="tablinks" onclick="openTab(event, 'Card')" value="Card" id="defaultOpen">Card</button>
      <button class="tablinks" onclick="openTab(event, 'List')" value="List">List</button>
      <div class="dropdown-sortby justify-content-between">
        <p></p>
        <div class="row align-items-center">
          <div class="select_wrap sortby">
              <ul class="default_option">
                  <li>
                      <p class="default-text">Sort By</p>
                  </li>
              </ul>
              <ul class="select_ul">
                <li class="form-check">
                  <label class="form-check-label"  for="user-input2"><input id="user-input2" class="form-check-input" type="radio"  name="harga" value="hargaplus" >
                    Harga+
                  </label>
                </li>
                <li class="form-check">
                  <label class="form-check-label"  for="user-input3"><input id="user-input3" class="form-check-input" type="radio"  name="harga" value="hargamin" >
                    Harga-
                  </label>
                </li>
                <li class="form-check">
                  <label class="form-check-label"  for="user-input4"><input id="user-input4" class="form-check-input" type="radio"  name="nama" value="namaplus" >
                    Nama+
                  </label>
                </li>
                <li class="form-check">
                  <label class="form-check-label"  for="user-input5"><input id="user-input5" class="form-check-input" type="radio"  name="nama" value="namamin" >
                    Nama-
                  </label>
                </li>
              </ul>
          </div>
        </div>
      </div>
      <script>document.getElementById("defaultOpen").click();</script>
    </div>

    {% include 'stock/results-partial.html' %}

    
  </div>




{% endblock content %}

stock/templates/stock/detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<script>
    $(document).on('click', '.confirm-delete', function(){
        return confirm('Are you sure you want to delete this?');
    })
</script>
<!-- KANAN -->
<div class="main-panel">
    <div class="content-wrapper">
        <div class="luar detail-page">

            <div class="rowss">
                <div class="columnss">
                    <img class="product-img-detail" src="{{ detail_product.get_photo_url }}">
                </div>
                <div class="columnss">
                    <h3 class="detail-title">{{detail_product.name}}</h3>
                    <h5 class="detail-category text-muted">{{detail_product.category|floatformat}}</h5>
                    <h5 class="detail-price">Harga : Rp {{detail_product.harga_jual|floatformat}}</h5>
                    <h5 class="detail-price">Modal : Rp {{detail_product.harga_modal|floatformat}}</h5>    
                    <h5 class="detail-price">Stok : {{detail_product.quantity|floatformat}} buah</h5>    
                    <h5 class="detail-price">Supplier : {{detail_product.supplier}}</h5>   
                    <h5 class="detail-price">Description : <h5>{{detail_product.description}}</h5></h5>   
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            {{ form|crispy }}
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-primary btn-buy " type="submit">Buy</button>
                            <a style='float: right;' class="btn btn-primary btn-merah" href="{% url 'stock:author-delete' slug=detail_product.slug pk=detail_product.pk %}">Delete</a>
                            <a style='float: right; margin-right: 10px;' class="btn btn-primary btn-hijau" href="{% url 'stock:author-update' slug=detail_product.slug pk=detail_product.pk %}">Update</a>
                        </div>
                    </form>
                </div>  
            </div>
        </div>
        <div class="luar table-page">
            <div class="infinite-container">   
                    <table>
                        <tr>
                        <th>Jumlah Pembelian</th>
                        <th>Total Harga</th>
                        <th>Jam</th>
                        <th>Tanggal</th>
                        <!-- <th>X</th> -->
                        <th>X</th>
                        </tr>
                        {% for Transaksi in data_transaksi %}
                            <tr>
                                <td>{{Transaksi.sold_quantity|floatformat}}</td>
                                <td>{{Transaksi.total}}</td>
                                <td>{{Transaksi.purchase_date.time|date:"H:i"}}</td>
                                <td>{{Transaksi.purchase_date.date}}</td>
                                <!-- <td><a href='{%url "stock:transaksi-delete" pk=Transaksi.pk %}'>X</a></td> -->
                                <td style="text-align: -webkit-center;"><form style="display:table-cell;" method="POST" action="{% url 'stock:transaksi-delete' pk=Transaksi.pk%}">{% csrf_token %}<button class="btn btn-merah" onclick="return confirm('Are you sure?');">X</button></form> </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% if data_transaksi.has_other_pages %}
                    <ul class="pagination pagination-sm container">
                        {% if data_transaksi.has_previous %}
                            <a class="btn btn-outline-info mb-4 but" href="?page=1">First</a>
                            <a class="btn btn-outline-info mb-4 but" href="?page={{ data_transaksi.previous_page_number }}">Previous</a>
                        {% endif %}
                            
                        {% for num in data_transaksi.paginator.page_range %}
                            {% if data_transaksi.number == num %}
                                <a class="btn btn-info mb-4 but" href="?page={{ num }}">{{ num }}</a>
                            {% elif num > data_transaksi.number|add:'-3' and num < data_transaksi.number|add:'3' %}
                                <a class="btn btn-outline-info mb-4 but" href="?page={{ num }}">{{ num }}</a>
                            {% endif %}
                        {% endfor %}
                            
                        {% if data_transaksi.has_next %}
                            <a class="btn btn-outline-info mb-4 but" href="?page={{ data_transaksi.next_page_number }}">Next</a>
                            <a class="btn btn-outline-info mb-4 but" href="?page={{ data_transaksi.paginator.num_pages }}">Last</a>
                        {% endif %}                       
                    </ul>
                {% endif %}             
            </div>    
        </div>
    </div>

 

    
{% endblock content %}